import { getAllPages } from '@/lib/api';
import { InferGetServerSidePropsType } from 'next';
import Head from 'next/head';

export default function Home(
    props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {props.pages.map((page) => {
                    return (
                        <div key={page.id}>
                            <h1>{page.title}</h1>
                            <p>{page.slug}</p>
                        </div>
                    );
                })}
            </main>
        </>
    );
}

export const getServerSideProps = async () => {
    try {
        const pages = await getAllPages();

        return {
            props: {
                pages: pages.docs,
            },
        };
    } catch (error) {
        return {
            notFound: true,
        };
    }
};
